name: Test Branch

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --all-groups

      - name: Lint Check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "check"

      - name: Format Check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "format --check"


      - name: Run tests
        run: uv run pytest src/tests
